"use client";

import { Header } from "@/components/Header";
import "../styles/app.scss";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { store } from "../redux/store";
import { Provider } from "react-redux";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "MioGesto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Provider store={store}>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
